Controllers/KullaniciController.cs
using DalbudakSigorta.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DalbudakSigorta.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;


namespace DalbudakSigorta.Controllers
{
    public class KullaniciController : Controller
    {

        private readonly DataContext _context;

        public KullaniciController(DataContext context)
        {
            _context = context;
        }

        // public IQueryable<Kullanici> Kullanicilar => _context.Kullanicilar;
        // public void CreateUser(Kullanici kullanici)
        // {
        //     _context.Kullanicilar.Add(kullanici);
        //     _context.SaveChanges();
        // }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var kullanicilar = await _context.Kullanicilar.ToListAsync();
            return View(kullanicilar);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Check if the user already exists
                var user = await _context.Kullanicilar
                    .FirstOrDefaultAsync(x => x.UserName == model.UserName || x.Eposta == model.Eposta);

                if (user == null)
                {
                    // Create a new user
                    var newUser = new Kullanici
                    {
                        UserName = model.UserName,
                        Eposta = model.Eposta,
                        Password = model.Password, // Password hashing should be implemented
                        KullaniciAd = model.KullaniciAd,
                        KullaniciSoyad = model.KullaniciSoyad,
                        BaslamaTarihi = DateTime.Now
                    };

                    // Add the new user to the context
                    _context.Kullanicilar.Add(newUser);
                    await _context.SaveChangesAsync(); // Save changes to the database

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Username or Email is already in use.");
                }
            }

            return View(model);
        }


        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kullan = await _context.Kullanicilar
                .Include(k => k.Araclar)
                .Include(k => k.Policeler)  // Include Policeler based on OnaylayanId
                .FirstOrDefaultAsync(k => k.KullaniciId == id);

            if (kullan == null)
            {
                return NotFound();
            }

            return View(kullan);
        }


        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Kullanici model)
        {
            if (id != model.KullaniciId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Kullanicilar.Any(o => o.KullaniciId == model.KullaniciId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }

            return View(model);
        }




        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kullanici = await _context.Kullanicilar.FindAsync(id);

            if (kullanici == null)
            {
                return NotFound();
            }

            return View(kullanici);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int id)
        {
            var kullanici = await _context.Kullanicilar.FindAsync(id);
            if (kullanici == null)
            {
                return NotFound();
            }
            _context.Kullanicilar.Remove(kullanici);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        public IActionResult Login()
        {
            if (User.Identity!.IsAuthenticated)
            {
                return RedirectToAction("Index", "Posts");
            }
            return View();
        }


        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Check if the user already exists
                var user = await _context.Kullanicilar
                    .FirstOrDefaultAsync(x => x.UserName == model.UserName || x.Eposta == model.Eposta);

                if (user == null)
                {
                    // Create a new user
                    var newUser = new Kullanici
                    {
                        UserName = model.UserName,
                        Eposta = model.Eposta,
                        Password = model.Password, // Currently, password hashing is not implemented.
                        KullaniciAd = model.KullaniciAd,
                        KullaniciSoyad = model.KullaniciSoyad,
                        BaslamaTarihi = DateTime.Now
                    };

                    // Add the new user to the context
                    _context.Kullanicilar.Add(newUser);
                    await _context.SaveChangesAsync(); // Save changes to the database

                    return RedirectToAction("Login");
                }
                else
                {
                    ModelState.AddModelError("", "Username or Email is already in use.");
                }
            }

            return View(model);
        }




        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {

            if (ModelState.IsValid)
            {
                var isUser = _context.Kullanicilar.FirstOrDefault(x => x.Eposta == model.Eposta && x.Password == model.Password);

                if (isUser != null)
                {
                    var userClaims = new List<Claim>();

                    userClaims.Add(new Claim(ClaimTypes.NameIdentifier, isUser.KullaniciId.ToString()));
                    userClaims.Add(new Claim(ClaimTypes.Name, isUser.UserName ?? ""));

                    if (isUser.Eposta == "admin@adayazilim.com")
                    {
                        userClaims.Add(new Claim(ClaimTypes.Role, "admin"));
                    }

                    var claimsIdentity = new ClaimsIdentity(userClaims, CookieAuthenticationDefaults.AuthenticationScheme);

                    var authProperties = new AuthenticationProperties
                    {
                        IsPersistent = true
                    };

                    await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity),
                        authProperties);

                    return RedirectToAction("Index", "Home");

                }
                else
                {
                    ModelState.AddModelError("", "Kullanıcı adı veya şifre yanlış");
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Login");
        }

    }
}

Controllers/MusteriController.cs
using DalbudakSigorta.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DalbudakSigorta.Controllers
{
    public class MusteriController : Controller
    {

        private readonly DataContext _context;

        public MusteriController(DataContext context)
        {
            _context = context;
        }

        [Authorize]
        public async Task<IActionResult> Index(string searchString)
        {
            var musteriler = await _context.Musteriler.ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                ViewBag.searchString = searchString;
                musteriler = musteriler.Where(p =>
                    (p.TCKimlik?.Contains(searchString) ?? false) ||
                    (p.AdSoyad?.ToLower().Contains(searchString) ?? false)
                ).ToList();
            }

            return View(musteriler);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Musteri model)
        {
            if (ModelState.IsValid)
            {
                _context.Musteriler.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var musteri = await _context.Musteriler
                                        .Include(m => m.Policeler) // Ensure Policeler is loaded
                                        .FirstOrDefaultAsync(m => m.MusteriId == id);

            if (musteri == null)
            {
                return NotFound();
            }

            return View(musteri);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // data açığı için önemli, kullanıcı token,'nin integrity'si için //Formu yükleyen kişi ile güncelleyen kişi aynı mı diye kontrol ettiğimiz token.
        public async Task<IActionResult> Edit(int id, Musteri model)
        {
            if (id != model.MusteriId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Musteriler.Any(o => o.MusteriId == model.MusteriId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }

            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var musteri = await _context.Musteriler.FindAsync(id);

            if (musteri == null)
            {
                return NotFound();
            }

            return View(musteri);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int id)
        {
            var musteri = await _context.Musteriler.FindAsync(id);
            if (musteri == null)
            {
                return NotFound();
            }
            _context.Musteriler.Remove(musteri);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DalbudakSigorta</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DalbudakSigorta.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DalbudakSigorta</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Musteri" asp-action="Index">Müşteriler</a>
                        </li>
                        @if(User.FindFirstValue(ClaimTypes.Role) == "admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Kullanici" asp-action="Index">Kullanıcılar</a>
                            </li>
                        }
                        
                        @if(User.Identity!.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a href="/police/index" class="nav-link">Policeler/Yeni Police</a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a href="/kullanici/logout" class="nav-link">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a href="/kullanici/login" class="nav-link">Login</a>
                            </li>
                            <li class="nav-item">
                                <a href="/kullanici/register" class="nav-link">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DalbudakSigorta - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>